# Generated by Django 4.2.19 on 2025-03-28 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_petprofile_favorite_food_petprofile_personality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petprofile",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="profiles.userprofile",
            ),
        ),
    ]
