# Generated by Django 4.2.19 on 2025-04-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_petprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="signature",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
