# Generated by Django 4.2.19 on 2025-04-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
