# Generated by Django 4.2.19 on 2025-03-18 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DogRunNew",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("prop_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("dogruns_type", models.CharField(max_length=100)),
                ("accessible", models.CharField(max_length=50)),
                ("notes", models.TextField(max_length=255)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="dogruns/"),
                ),
                ("google_name", models.TextField(blank=True, null=True)),
                ("borough", models.TextField(blank=True, null=True)),
                ("zip_code", models.TextField(blank=True, null=True)),
                ("formatted_address", models.TextField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("additional", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "dog_runs_new",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("rating", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="parks.dogrunnew",
                    ),
                ),
            ],
            options={
                "db_table": "park_reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
