# Generated by Django 2.2 on 2025-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dogrun",
            name="dogruns_type",
            field=models.CharField(max_length=100),
        ),
    ]