# Generated by Django 4.2.19 on 2025-03-19 07:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0004_dogrunnew"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dogrunnew",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
