# Generated by Django 4.2.19 on 2025-03-19 08:09

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0005_alter_dogrunnew_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dogrunnew",
            name="image",
        ),
        migrations.CreateModel(
            name="ParkImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                (
                    "park",
                    models.ForeignKey(
                        db_column="park_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="parks.dogrunnew",
                    ),
                ),
            ],
        ),
    ]
