# Generated by Django 4.2.19 on 2025-04-06 22:01

from django.db import migrations, models


def copy_google_name_to_display_name(apps, schema_editor):
    DogRunNew = apps.get_model("parks", "DogRunNew")
    for park in DogRunNew.objects.all():
        park.display_name = park.google_name
        park.save()


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0010_imagereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="dogrunnew",
            name="display_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(copy_google_name_to_display_name),
    ]
