# Generated by Django 4.2.19 on 2025-04-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0012_dogrunnew_slug_alter_dogrunnew_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dogrunnew",
            name="slug",
            field=models.SlugField(),
        ),
    ]
