# Generated by Django 4.2.19 on 2025-04-08 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0013_alter_dogrunnew_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkimage",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="parks.review",
            ),
        ),
    ]
