# Generated by Django 4.2.19 on 2025-04-16 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parks", "0014_parkimage_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkimage",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parkimage",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parkimage",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who removed the image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
