# Generated by Django 4.2.19 on 2025-04-16 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0015_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="parent_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_replies",
                to="parks.reply",
            ),
        ),
    ]
