# Generated by Django 4.2.19 on 2025-04-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0015_remove_dogrunnew_display_name_remove_dogrunnew_slug_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DogEvent",
        ),
    ]
