# Generated by Django 4.2.19 on 2025-04-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0015_parkimage_is_removed_parkimage_removed_at_and_more"),
        ("parks", "0015_parkpresence"),
    ]

    operations = []
