# Generated by Django 4.2.19 on 2025-04-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0016_delete_dogevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(verbose_name="Message Content"),
        ),
    ]
