# Generated by Django 4.2.19 on 2025-04-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0016_merge_20250416_1154"),
        ("parks", "0017_alter_reply_parent_reply_replyreport"),
    ]

    operations = []
