# Generated by Django 4.2.19 on 2025-04-16 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parks", "0017_alter_reply_parent_reply_replyreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews_removed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
