# Generated by Django 4.2.19 on 2025-04-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0019_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
