# Generated by Django 4.2.19 on 2025-04-29 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parks", "0020_reply_is_deleted_review_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkInfoReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_dogruns_type",
                    models.CharField(
                        choices=[("Off-Leash", "Off-Leash"), ("Run", "Run")],
                        max_length=20,
                    ),
                ),
                ("new_accessible", models.BooleanField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_handled", models.BooleanField(default=False)),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info_reports",
                        to="parks.dogrunnew",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
