# Generated by Django 4.2.19 on 2025-05-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0022_reply_is_removed_reply_removed_at_reply_removed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="is_removed_permanently",
            field=models.BooleanField(default=False),
        ),
    ]
