# Generated by Django 4.2.19 on 2025-04-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreport",
            name="category",
            field=models.CharField(
                choices=[
                    ("SPAM", "Spam or Junk"),
                    ("HARASSMENT", "Harassment or Bullying"),
                    ("HATE_SPEECH", "Hate Speech"),
                    ("IMPERSONATION", "Impersonation"),
                    ("INAPPROPRIATE", "Inappropriate Content"),
                    ("OTHER", "Other (Please specify)"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="Report Category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userreport",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text='If you selected "Other", please provide details here.',
                verbose_name="Detailed Reason",
            ),
        ),
    ]
