# Generated by Django 4.2.19 on 2025-04-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0002_userreport_category_alter_userreport_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreport",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text="You can provide specific details about the report here, if necessary.",
                verbose_name="Optional details",
            ),
        ),
    ]
